# -*- coding: utf-8 -*-
"""count no of objects in a image uisng YOLO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14QP10BL-khx4UM9ob1uaJpHMsF7j8Dv6
"""

import cv2
# import numpy as np
import matplotlib.pyplot as plt
import cvlib as cv
from cvlib.object_detection import draw_bbox
from numpy.lib.polynomial import poly

img = cv2.imread('/content/opp1.jpg')
# img = cv2.imread('C:/Users/ranve/Desktop/count/test3.jfif')


img1 = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.figure(figsize=(50,50))
#plt.imshow(img1)


box, label, count = cv.detect_common_objects(img)
output = draw_bbox(img, box, label, count)

output = cv2.cvtColor(output, cv2.COLOR_BGR2RGB)
plt.figure(figsize=(25,25))
plt.axis("off")
plt.imshow(output)
plt.show()

print("Number of objects in this image are " + str(len(label)))

!pip install cvlib

import torch
import numpy as np
import cv2
model=torch.hub.load('ultralytics/yolov5','yolov5s')
cap=cv2.VideoCapture(0)
while cap.isOpened():
  ret,frame=cap.read()
  res=model(frame)
  cv2.imshow('YOLO',np.squeeze(result.render()))
  if cv2.waitKey(10)&0xFF==ord('q'):
    break;
cap.release()
cv2.destroyAllWindows()